### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by LukasBommes** [LukasBommes/mv-extractor#57]
When installing the Python package for release 1.0.6 with `python -m pip install motion-vector-extractor` in a fresh Python3.10 environment and then running `extract_mvs -h` you may get this error:

```
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
Traceback (most recent call last):
  File "/home/lukas/experiments/installmvs/env/bin/extract_mvs", line 5, in <module>
    from mvextractor.__main__ import main
  File "/home/lukas/experiments/installmvs/env/lib/python3.10/site-packages/mvextractor/__main__.py", line 8, in <module>
    import cv2
  File "/home/lukas/experiments/installmvs/env/lib/python3.10/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
```

The issue is that numpy 2, which was released in June 2024, is not ABI-compatible with numpy 1. This means code that was built against numpy 1 does not work with numpy 2 as a runtime dependency. To support numpy 2 as a runtime dependency, code has to be built against numpy 2. For details see [here](https://numpy.org/doc/stable/dev/depending_on_numpy.html).

To prevent this bug I would have had to timely rebuild the source against numpy 2, which I didn't do. 
With release 1.1.0 of the motion-vector-extractor this problem is now resolved.

**Comment by LukasBommes** [comment]
Releaee 1.0.6 still functions properly once you manually downgrade to numpy 1.x after the installation of motion-vector-extractor.
